fix: refactor to improve readability of main_page function
sas-fossdev/saspes pull request #230
Opened 2020-11-09 01:37 UTC by priime0

When initially browsing through the codebase, it was very difficult to grasp what all the lines of code were doing. I took the time to move verbose blocks of code into functions whose names hopefully describe what they were doing. By representing these blocks with single-line functions, it makes it easier to understand what the `main_page` function is trying to do, and thus less intimidating to contribute to.

I additionally rebased my commits to make their subject lines more consistent with one another, and in doing so, accidentally made myself a contributor to the `9eceaf4` commit, so ignore that. My commit messages further detail my line of reasoning for specific chunks in the code.

2020-11-11 22:57 UTC, gary-kim commented on src/js/saspowerschoolff.js
> +function getFirstSemCourses () {
You want to just change this to be an async function? Something like this?
```javascript
async function getFirstSemCourses () {
    return await (await fetch("https://powerschool.sas.edu.sg/guardian/termgrades.html")).text()
}
```

2020-11-16 07:33 UTC, Suhas-13 requested changes
It seems like hypothetical assignment breaks with this, generates a value of NaN regardless of what percent / grade is used.

2020-11-16 07:36 UTC, Suhas-13 commented on src/js/saspowerschoolff.js
> +    addHypoAssignment();
I think this is missing a parameter which is breaking hypoAssignment, try adding number as a parameter here.

2020-11-16 09:59 UTC, Suhas-13 approved these changes

2020-11-16 11:08 UTC, merged