added last seen grades feature, updated various links in extension op…
sas-fossdev/saspes pull request #232
Opened 2020-11-25 14:33 UTC by Suhas-13

I added the  last seen grades feature + ui, and  updated various links in extension options/other pages.

Signed-off-by: Suhas Hariharan <hariharan774531@sas.edu.sg>

2020-11-25 16:59 UTC, gary-kim requested changes

2020-11-25 16:59 UTC, gary-kim commented on src/js/components/ExtensionInfo.vue
> +                    href="hhttps://github.com/sas-fossdev/saspes/blob/master/CHANGELOG.md"
```suggestion
                    href="https://github.com/sas-fossdev/saspes/blob/master/CHANGELOG.md"
```

2020-11-25 16:59 UTC, gary-kim commented on src/js/components/LastGrades.vue
> +        // Due to an issue with Vue reactivity not working on Course instances, using a standard JS object instead
Take a look for how this kind of problem was fixed in Nextcloud:
https://github.com/nextcloud/server/blob/a2cedcefeedd68790d72aca9102ce17558b407fa/apps/files_sharing/src/models/Share.js#L45-L58
https://github.com/nextcloud/server/blob/a2cedcefeedd68790d72aca9102ce17558b407fa/apps/files_sharing/src/mixins/SharesMixin.js#L63-L67

2020-11-25 16:59 UTC, gary-kim commented on src/js/helpers.js
> + *  @async
```suggestion
 * @async
```

2020-11-25 16:59 UTC, gary-kim commented on src/js/helpers.js
> +        const assignment = new Assignment(curr[2] ? curr[2].innerText : "", curr[curr.length - 1] ? curr[curr.length - 1].innerText : "", i);
Just looks cleaner but your choice :)
```suggestion
        const assignment = new Assignment(curr[2]?.innerText || "", curr[curr.length - 1]?.innerText || "", i);
```

2020-11-25 16:59 UTC, gary-kim commented on src/js/helpers.js
> +    return new Promise((resolve) => {
This is an async function so it already returns a promise. Now you're returning a promise that resolves to a promise. You can just do 
```javascript
const output = browser.storage.local.get("USERDATA_" + username)
```

2020-11-25 16:59 UTC, gary-kim commented on src/js/saspowerschoolff.js
> +                                course: courses[courses.length - 1],
I think you may run into some race conditions here because these are going to be running at the same time.

2020-11-25 16:59 UTC, gary-kim commented on src/js/saspowerschoolff.js
> +    (browser.storage.local.get("most_recent_user")).then(output => {
I'd recommend just making the function an `async` so you can use `await`. Just a recommendation.

2020-11-25 16:59 UTC, gary-kim commented on src/js/components/ClassGrade.vue
> -    },
Any particular reason you moved this logic out? Just curious.

2020-11-25 16:59 UTC, gary-kim commented on src/js/components/ClassGrade.vue
> +
Also, unnecessary newline

2020-11-26 02:13 UTC, Suhas-13 commented on src/js/components/ClassGrade.vue
> -    },
yeah, for the save grades feature the finalPercent needs to be included in the course object and currently, this code was doing it but not actually modifying the course object, so I just moved it out so that it also updates the course object.

2020-11-26 02:15 UTC, Suhas-13 commented on src/js/components/LastGrades.vue
> +        // Due to an issue with Vue reactivity not working on Course instances, using a standard JS object instead
is reactivity needed for the last grades though? I don't think it'd ever be updating except after a login/logout.

2020-11-26 02:22 UTC, Suhas-13 commented on src/js/saspowerschoolff.js
> +                                course: courses[courses.length - 1],
I thought using promises would fix that since it only calculates the GPA once all of them have been resolved. Is there another possible implication?

2020-11-26 02:23 UTC, Suhas-13 commented on src/js/saspowerschoolff.js
> +    (browser.storage.local.get("most_recent_user")).then(output => {
sorry, which function are you referring to here? the actual main_page function?

2020-11-26 02:32 UTC, Suhas-13 commented on src/js/helpers.js
> +    return new Promise((resolve) => {
Thanks for the review, does my recent commit fix that? Sorry it was pretty late when I wrote most of this and I didn't really bother looking into how exactly promises are supposed to be used(so much as just tried every combination until it worked).

2020-11-26 02:43 UTC, Suhas-13 commented
closes #227

2020-11-28 05:47 UTC, Suhas-13 commented
@gary-kim I think I've made the changes you requested, could you please approve it so I can go ahead and merge the pull request? I'd like to get the update pushed before exams so that it can save people's last seen grades.

2020-11-28 05:47 UTC, priime0 commented
lgtm :+1:

2020-11-28 05:52 UTC, gary-kim commented on src/js/components/LastGrades.vue
> +        // Due to an issue with Vue reactivity not working on Course instances, using a standard JS object instead
I was mentioning this so that you don't have to reimplement the course class here, pretty much. You know what? Let's refactor this later :)

2020-11-28 05:54 UTC, gary-kim approved these changes

2020-11-28 05:54 UTC, gary-kim commented
@priime0 You can go to the review tab and make an approving review :)

2020-11-28 06:14 UTC, priime0 approved these changes

2020-11-28 06:25 UTC, merged