Weighting
sas-fossdev/saspes pull request #248
Opened 2020-12-26 08:46 UTC by ARtheboss

2020-12-26 08:57 UTC, Suhas-13 commented
Seems to be some lint errors when calling npm test, the category weighting is also not displaying for me when I load it in due to an issue with the new Vue component.

2020-12-26 17:18 UTC, gary-kim submitted a review, later dismissed
Could you remove the `.vscode` files from your PR?
For the linting errors, most of them can be fixed with `npm run eslint:fix`. Most of them seem to be from simple things like missing semicolon so should not be too difficult to fix.

2020-12-27 02:58 UTC, Suhas-13 commented
Also once you are able to get that fixed, I really think it would be beneficial to keep the existing assignment view as the default with a button at the bottom to toggle to category weightings and back. Anecdotally, I know several students who are unaware of how category weighing works and would be extremely confused to see that when they open up PowerSchool. However, I haven't been able to see the final view yet, due to the error message I sent you, so it may not be as confusing as I would expect for category weighting.

2020-12-27 02:59 UTC, Suhas-13 commented
Also these two commits, https://github.com/sas-fossdev/saspes/pull/248/commits/196560a787de5dd1efff4a014262b828c8efcfe1 and https://github.com/sas-fossdev/saspes/pull/248/commits/24f7e16d5e764da9e3ac5a8abb43abf52b370a9e seem to be missing a DCO which is causing that check to fail.

2020-12-27 03:31 UTC, Suhas-13 commented
I just reviewed it, and I think it really would be better to have a button to enable category weighting that would automatically hide the old hypothetical assignment and vice versa. It can be confusing to a user who is unfamiliar and some users might think that the hypothetical assignment is part of the category weighting even though they are independent.

2020-12-27 03:36 UTC, Suhas-13 commented
I think given that some users may be unfamiliar with how this works, it might also be beneficial to have a dialog box that explains what this is and it's drawbacks when the toggle button is pressed initially.

2020-12-31 05:55 UTC, Suhas-13 commented
I just went through it again, the UI looks fine, although the wording might need to be changed a bit to fix grammar/wording and to make it more clear what category weighting is. Also, I think the commit history might've gotten a bit messed up since this PR now seems to be including a bunch of other commits.

2020-12-31 06:01 UTC, Suhas-13 requested changes

2020-12-31 06:01 UTC, Suhas-13 commented on src/js/helpers.js
> +    browser.storage.local.set(data);
if there are two users on the same computer that have a course in common, this would overwrite that data. it would probably be better to use the current storage structure we are using from https://github.com/sas-fossdev/saspes/pull/243 and store it in user_data.

2020-12-31 06:02 UTC, Suhas-13 requested changes

2020-12-31 06:02 UTC, Suhas-13 commented on src/js/components/CategoryWeighting.vue
> +        <p>Enter the decimal weighting of each category (from your course syllabus) and use exemptions and add assignment on the table above to add multiple hypothetical grades.</p>
You might want to revise the wording/grammar here and also explain a bit more about how category weighting works.

2021-02-01 01:34 UTC, closed without merging